### ISSUE TITLE
Template error while trying to deploy via Cloud Formation template

### ISSUE THREAD

**Issue by marciobuss** [awslabs/live-stream-on-aws#5]
Hello,
I have done all the steps required to deploy this stack via Cloud Formation, created the bucket that needs to be manually created and everything else. When I try to "Create Stack" via CloudFormation template, I am getting a "CREATE_FAILED" error when the template tries to create a lambda function:

Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 93428ea8-04cd-11e9-9121-07856613c30c)

This has nothing to do with the bucket that I need to manually create, this has been done. I am aware that it is related to other buckets that the template itself creates. I am also getting a "CREATE_FAILED" error when the template tries to create another bucket, , but what I dont understand is that when I access my S3 console I actually see the additional bucket the template was trying to create and reported failing. It would be awesome if someone could help with the issue.

PS.: when I try to simply visualize the template on "Design", after having copied the template URL into the text box, there is already a syntax error (even before pressing the "Next" button).

Thank you very much,
Marcio

**Comment by marciobuss** [comment]
Some additional comments: if I use the template with the default bucket called "solutions", meaning I do not git clone the code nor run the shell script, etc. but alternatively launch the solution via https://docs.aws.amazon.com/solutions/latest/live-streaming/deployment.html, then things actually work. However I don't believe this is the expected result, I would expect the user to create his/her own bucket, run the shell script, sync the s3 bucket, and then create the stack.

**Comment by vijaysat1** [comment]
The S3 bucket has to be manually created and the lambda zip file placed in the bucket , incase of adhoc deployment rather than using (https://docs.aws.amazon.com/solutions/latest/live-streaming/deployment.html), please verify the depoloyment process with bucket creation process below

Readme.md
2. Create the deployment packages:

Run the build-s3-dist.sh script, passing in 2 variables:

    CODEBUCKET = the name of the S3 bucket (do NOT include the -region extension)
    CODEVERSION = this will be the subfolder containing the code.

This will:

    copies the console files to ./deployment/dist/.
    copies the CloudFormation template to ./deployment/dist/ and updates the source code mappings.
    zips and copies the source code to ./deployment/dist/

Example:
  cd deployment/
  ./build-s3-dist.sh bucket 1.01

This will deploy the source code to:
  s3://bucket-us-east-1/live-streaming-on-aws/1.01/.
And update the CloudFormation template mappings:
  SourceCode:
    General:
      S3Bucket: bucket
      KeyPrefix: live-streaming-on-aws/1.01
3. Upload the Code to Amazon S3.

Use the AWS CLI to sync the lambda code and demo console files to amazon S3:
  cd deployment/
  aws s3 sync .dist/ s3://bucket-us-east-1/live-streaming-on-aws/1.01/.

**Comment by bastianbb** [comment]
I have the exact same problem with this solution: https://github.com/awslabs/video-on-demand-on-aws
I think that the problem could be related because the deployment process is the same.

**Comment by andresrivero** [comment]
Hi @bastianbb and @marciobuss,
Are you running the build sh script and aws cli commands on Windows?

**Comment by marciobuss** [comment]
Nope, I used Ubuntu Linux. But to be honest I have not tried running the
scripts again, I went on and simply used the pre-cooked "template button"
which triggers the creation process thru the web browser.

**Comment by andresrivero** [comment]
Gotcha. I found that in Windows, it usually wouldn't create the two console ZIP files (console-resource-js and console-resource-py) in the dist folder. The missing ZIP files would trigger the S3 GetObject Error for me, using Linux & Mac fixed that for me - since it created the ZIP files everytime using the build sh

**Comment by tomnight** [comment]
The build scripts where intended for us in a Linux/mac environment not windows. We'll take a look at this for the next release and either incorporate windows support or update the documentation accordingly. Thanks for the feedback.

**Comment by durgendra** [comment]
I was facing similar issue. The solution for me to add region name in the S3 bucket name
e.g. 
S3 Bucket: bucket-us-east-1

While in the template it is

Mappings:
  SourceCode:
    General:
      S3Bucket: bucket
     ........
